baseURL = 'https://saurav-shrivastav.github.io/'
languageCode = 'en-us'
title = 'Saurav Shrivastav'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Papershelf"
    url = "/papershelf/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[params]
  description = "Personal portfolio and blog"
  author = "Saurav Shrivastav"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
